# Generated by Django 4.0.3 on 2023-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_person_id_alter_trains_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trains',
            name='id',
        ),
        migrations.AddField(
            model_name='trains',
            name='train_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
